name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.20.1
  - pandas=1.4.4
  - numpy=1.23.3
  - matplotlib=3.6.0
  - scipy=1.9.1
  - statsmodels=0.13.2
  - seaborn=0.12.0
  - scikit-learn=1.1.2
  - numba=0.56.2
  - jupyter=1.0.0
  - xarray=0.19.0
  - netCDF4=1.5.7
  - Bottleneck=1.3.2
  - dask=2021.9.1
  - climlab=0.7.12
  - pip
  - python=3.9.7
  - libstdcxx-ng=12.1.0
  - pip:
    - pathos=0.2.9
    - tqdm=4.64.1
    - tftb=0.1.4
    - pyhht=0.1.0
    - wget=3.2
    - nitime=0.9
    - tabulate=0.8.10
    - Unicode=1.3.4
    - pyleoclim==0.9.1
