name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.21.0
  - jupyter=1.0.0
  - xarray=2022.6.0
  - netCDF4=1.5.8
  - Bottleneck=1.3.4
  - dask=2022.8.0
  - climlab=0.7.13
  - pip
  - python=3.9.13
  - libstdcxx-ng=12.1.0
  - pip:
    - pyleoclim==0.9.1
