name: pyleoclimPaper
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - xarray
  - netCDF4
  - Bottleneck
  - dask
  - climlab
  - pip
  - python>3.11
  - 
  - pip:
    - git+https://github.com/LinkedEarth/pylipd.git@main
    - pyleoclim
